---
- name: Update NTP servers 
  hosts: all
  become: true

  tasks:
  - name: Fill the blank line after a specific header
    ansible.builtin.lineinfile:
      path: /etc/chrony.conf
      regex: '^time.cloudflare.com iburst'
      line: 'pool 2.pool.ntp.org iburst'

  - name: Restart chronyd service
    service:
      name: chronyd
      state: restarted
      
