---
- name: Update sshd configuration
  hosts: all
  become: true

  tasks:
  - name: Disable root login
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regex: '^PermitRootLogin'
      line: 'PermitRootLogin no'
      state: present

  - name: Disable password authentication
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regex: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present 
    notify: 
      - Reload sshd

  handlers:
     - name: Reload sshd
       service:
         name: sshd
         state: restart  

